[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
buildCommand = ""

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
